---
title: "Extract Model Outputs"
author: "Mohamed Albirair"
<<<<<<< HEAD
date: "9/17/2021"
output: html_document
=======
<<<<<<< HEAD
date: "9/17/2021"
output: html_document
=======
geometry: "left = 1cm, right = 1cm, top = 1cm, bottom = 1.5cm"
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}  #make every figure with caption = h, this was the fix
  - \usepackage{setspace}\setstretch{1.25}
  - \usepackage{xcolor}
output:
  bookdown::pdf_document2:
        toc: true
fig_caption: yes
urlcolor: blue
>>>>>>> 69ba6d219856e2f83c00ee3c82252f33b2d93797
>>>>>>> 795cafbfaa751184f804bd88d35e3d1fc5ebf3ba
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, results = 'hold', warning = FALSE,
                      message = FALSE, error = FALSE, fig.height = 3.4)
pacman::p_load(tidyverse)
```

# Linear models

<<<<<<< HEAD
Below is a function that extracts linear models outputs (or `glm()` models with `family = "gaussian"` specification). Please note that the different variables will need to be named in a separate command (as in the following chunk).
=======
<<<<<<< HEAD
Below is a function that extracts linear models outputs (or `glm()` models with `family = "gaussian"` specification). Please note that the different variables will need to be named in a separate command (as in the following chunk).
=======
Below is a fuction that extracts linear models outputs (or `glm()` models with `family = "gaussian"` specification). Please note that the different variables will need to be named in a separate command (as in the following chunk).
>>>>>>> 69ba6d219856e2f83c00ee3c82252f33b2d93797
>>>>>>> 795cafbfaa751184f804bd88d35e3d1fc5ebf3ba

```{r linear model ouptut, results='hide'}

# mod <- lm({outcome} ~ {predictor} + {covariate1} + {covariate}, data = {dataset})
lmmod <- lm(mpg ~ cyl + gear + hp, data = mtcars)

lmOutputExtract <- function(mod){
      lmOutput <- data.frame(coefficients(summary(mod))[, c(1, 4)], confint(mod)) %>%
            dplyr::select(1, 3, 4, 2) %>% round(., 3) %>%
            `colnames<-`(c("Coefficient", "LCL", "UCL", "P-value")) %>%
            mutate(`P-value` = case_when(`P-value` < 0.001 ~ "<0.001*",
                                         `P-value` < 0.05 ~ paste0(`P-value`,"*"),
                                         `P-value` >= 0.05 ~ as.character(`P-value`)))
      print(lmOutput)
}

# linearOuptut <- lmOutputExtract(mod)
linearOutput <- lmOutputExtract(lmmod)
```

```{r q1aOutput}
linearOuptut %>%
      knitr::kable("latex", caption = "Linear regression model output") %>%
      kableExtra::kable_styling(latex_options = c("striped", "HOLD_position"), fixed_thead = T)
```